package tokens

import "github.com/sunshower-io/updraft/common/tokens"

const (
    ALREADY_FORWARDED           tokens.ErrorCode = "Already specified in FORWARD"
    IDENTIFIER_REDEFINED        tokens.ErrorCode = "Redefined identifier"
    IDENTIFIER_UNDEFINED        tokens.ErrorCode = "Undefined identifier"
    INCOMPATIBLE_ASSIGNMENT     tokens.ErrorCode = "Incompatible types"
    INVALID_ASSIGNMENT          tokens.ErrorCode = "Invalid assignment statement"
    INVALID_CHARACTER           tokens.ErrorCode = "Invalid character"
    INVALID_CONSTANT            tokens.ErrorCode = "Invalid constant"
    INVALID_EXPONENT            tokens.ErrorCode = "Invalid exponent"
    INVALID_EXPRESSION          tokens.ErrorCode = "Invalid expression"
    INVALID_FIELD               tokens.ErrorCode = "Invalid field"
    INVALID_FRACTION            tokens.ErrorCode = "Invalid fraction"
    INVALID_IDENTIFIER_USAGE    tokens.ErrorCode = "Invalid identifier usage"
    INVALID_INDEX_TYPE          tokens.ErrorCode = "Invalid index type"
    
    INVALID_NUMBER              tokens.ErrorCode = "Invalid Number"
    INVALID_STATEMENT           tokens.ErrorCode = "Invalid statement"
    
    INVALID_SUBRANGE_TYPE       tokens.ErrorCode = "Invalid subrange type"
    
    INVALID_TARGET              tokens.ErrorCode = "Invalid assignment target"
    INVALID_TYPE                tokens.ErrorCode = "Invalid type"
    INVALID_VAR_PARAM           tokens.ErrorCode = "Invalid VAR parameter"
    INVALID_GT_MAX              tokens.ErrorCode = "Minimum limit greater than maximum limit"
    MISSING_BEGIN               tokens.ErrorCode = "Missing BEGIN"
    MISSING_COLON               tokens.ErrorCode = "Missing ':'"
    MISSING_COLON_EQUALS        tokens.ErrorCode = "Missing ':='"
    MISSING_COMMA               tokens.ErrorCode = "Missing ','"
    MISSING_CONSTANT            tokens.ErrorCode = "Missing constant"
    MISSING_DO                  tokens.ErrorCode = "Missing 'DO'"
    MISSING_DOT_DOT             tokens.ErrorCode = "Missing '..'"
    MISSING_END                 tokens.ErrorCode = "Missing END"
    MISSING_EQUALS              tokens.ErrorCode = "Missing Equals"
    MISSING_FOR_CONTROL         tokens.ErrorCode = "Missing for control variable"
    MISSING_IDENTIFIER          tokens.ErrorCode = "Missing identifier"
    MISSING_LEFT_BRACKET        tokens.ErrorCode = "Missing '['"
    MISSING_OF                  tokens.ErrorCode = "Missing OF"
    MISSING_PERIOD              tokens.ErrorCode = "Missing '.'"
    MISSING_PROGRAM             tokens.ErrorCode = "Missing 'PROGRAM'"
    MISSING_RIGHT_BRACKET       tokens.ErrorCode = "Missing ']'"
    MISSING_RIGHT_PAREN         tokens.ErrorCode = "Missing ')'"
    MISSING_SEMICOLON           tokens.ErrorCode = "Missing ';'"
    MISSING_THEN                tokens.ErrorCode = "Missing THEN"
    MISSING_TO_DOWNTO           tokens.ErrorCode = "Missing 'TO' or 'DOWNTO'"
    MISSING_UNTIL               tokens.ErrorCode = "Missing 'Until'"
    MISSING_VARIABLE            tokens.ErrorCode = "Missing variable"
    CASE_CONSTANT_REUSED        tokens.ErrorCode = "CASE constant reused"
    NOT_CONSTANT_IDENTIFIER     tokens.ErrorCode = "Not a constant identifier"
    NOT_RECORD_VARIABLE         tokens.ErrorCode = "Not a record variable"
    NOT_TYPE_IDENTIFIER         tokens.ErrorCode = "Not a type identifier"
    RANGE_INTEGER               tokens.ErrorCode = "Integer literal out of range"
    RANGE_REAL                  tokens.ErrorCode = "Real literal out of range"
    STACK_OVERFLOW              tokens.ErrorCode = "Stack overflow"
    TOO_MANY_LEVELS             tokens.ErrorCode = "Nesting level too deep"
    TOO_MANY_SUBSCRIPTS         tokens.ErrorCode = "Too many subscripts"
    UNEXPECTED_EOF              tokens.ErrorCode = "Unexpected EOF"
    UNEXPECTED_TOKEN            tokens.ErrorCode = "Unexpected token"
    UNIMPLEMENTED               tokens.ErrorCode = "Unimplemented"
    UNRECOGNIZABLE              tokens.ErrorCode = "Unrecognizable input"
    WRONG_NUMBER_OF_PARAMS      tokens.ErrorCode = "Wrong number of parameters"
    
   
)
